# Generated by Django 5.1.7 on 2025-03-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('editor', 'Éditeur'), ('viewer', 'Spectateur')], default='admin', help_text='Rôle de l’utilisateur dans le système', max_length=10, verbose_name='Rôle'),
        ),
    ]
