# Generated by Django 5.1.7 on 2025-03-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(db_index=True, help_text='Date et heure de l’événement', verbose_name='Date de l’événement')),
                ('details', models.TextField(blank=True, help_text='Description ou informations supplémentaires', verbose_name='Détails')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Indique si le programme est visible publiquement', verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('game', models.ForeignKey(help_text='Le jeu auquel ce programme est associé', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='games.game', verbose_name='Jeu')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['event_date', 'is_published'], name='programmes__event_d_27116a_idx'), models.Index(fields=['game', 'event_date'], name='programmes__game_id_50c2b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('game', 'event_date'), name='unique_program_per_game_date')],
            },
        ),
    ]
